" install vim-plug if necessary
if has('win32')
  silent !iwr -useb https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim | ni $HOME/vimfiles/autoload/plug.vim -Force
else
  if empty(glob('~/.vim/autoload/plug.vim'))
    silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
      \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
  endif
endif

call plug#begin('~/.vim/plugged')

Plug 'itchyny/lightline.vim'
Plug 'scrooloose/nerdtree'
Plug 'Xuyuanp/nerdtree-git-plugin'
Plug 'airblade/vim-gitgutter'
Plug 'FriesischScott/monokai-pro'
Plug 'ntpeters/vim-better-whitespace'
Plug 'sheerun/vim-polyglot'
Plug 'RRethy/vim-hexokinase'

call plug#end()

" show lightline
set laststatus=2

" toggle nerdtree
map <C-o> :NERDTreeToggle<CR>

" use monokai theme
colorscheme monokai_pro_machine

if (has("termguicolors"))
  set termguicolors
endif

let g:Hexokinase_highlighters = ['sign_column']
" disable backups
:set nobackup

" configure tabs
:set tabstop=4
:set shiftwidth=0
:set expandtab

autocmd FileType yaml,yml setlocal et ts=2 ai sts=0 sw=2
