" install vim-plug if necessary
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin('~/.vim/plugged')

Plug 'itchyny/lightline.vim'
Plug 'scrooloose/nerdtree'
Plug 'Xuyuanp/nerdtree-git-plugin'
Plug 'airblade/vim-gitgutter'
Plug 'patstockwell/vim-monokai-tasty'
Plug 'ntpeters/vim-better-whitespace'
Plug 'JuliaEditorSupport/julia-vim'

call plug#end()

" show lightline
set laststatus=2

" toggle nerdtree
map <C-o> :NERDTreeToggle<CR>

" use monokai theme
let g:vim_monokai_tasty_italic = 1
colorscheme vim-monokai-tasty
let g:lightline = {
      \ 'colorscheme': 'monokai_tasty',
      \ }
if (has("termguicolors"))
  set termguicolors
endif

" disable backups
:set nobackup

" configure tabs
:set tabstop=4
:set shiftwidth=0
:set expandtab
